INSERT INTO gifs (title, description, url, thumbnail_url, tags, category, width, height, trending, featured) VALUES
('Happy Dance', 'Person dancing with joy', 'https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif', 'https://media.giphy.com/media/3o7abKhOpu0NwenH3O/200.gif', ARRAY['happy', 'dance', 'celebration'], 'emotions', 480, 270, true, true),
('Thumbs Up', 'Classic thumbs up approval', 'https://media.giphy.com/media/111ebonMs90YLu/giphy.gif', 'https://media.giphy.com/media/111ebonMs90YLu/200.gif', ARRAY['thumbs', 'approval', 'good'], 'reactions', 500, 375, true, false),
('Laughing', 'Person laughing out loud', 'https://media.giphy.com/media/3o7aCRloybJlXpNjSU/giphy.gif', 'https://media.giphy.com/media/3o7aCRloybJlXpNjSU/200.gif', ARRAY['laugh', 'funny', 'humor'], 'emotions', 480, 360, false, true),
('Heart Eyes', 'Love and admiration expression', 'https://media.giphy.com/media/3o6Zt7g9nH1nFGeBcQ/giphy.gif', 'https://media.giphy.com/media/3o6Zt7g9nH1nFGeBcQ/200.gif', ARRAY['love', 'heart', 'admiration'], 'emotions', 480, 270, true, false),
('Clapping', 'Enthusiastic applause', 'https://media.giphy.com/media/7rj2ZgttvgomY/giphy.gif', 'https://media.giphy.com/media/7rj2ZgttvgomY/200.gif', ARRAY['clap', 'applause', 'congratulations'], 'reactions', 500, 281, false, false),
('Mind Blown', 'Head exploding with amazement', 'https://media.giphy.com/media/26ufdipQqU2lhNA4g/giphy.gif', 'https://media.giphy.com/media/26ufdipQqU2lhNA4g/200.gif', ARRAY['mind', 'blown', 'amazed'], 'reactions', 480, 270, true, true),
('Crying Laughing', 'Tears of joy from laughter', 'https://media.giphy.com/media/3o6UBlHJQT19wSgJQk/giphy.gif', 'https://media.giphy.com/media/3o6UBlHJQT19wSgJQk/200.gif', ARRAY['crying', 'laugh', 'tears'], 'emotions', 480, 270, false, false),
('Facepalm', 'Classic facepalm reaction', 'https://media.giphy.com/media/XsUtdIeJ0MWMo/giphy.gif', 'https://media.giphy.com/media/XsUtdIeJ0MWMo/200.gif', ARRAY['facepalm', 'disappointed', 'oops'], 'reactions', 500, 375, false, true),
('Waving Hello', 'Friendly greeting wave', 'https://media.giphy.com/media/3ornka9rAaKRA2Rkac/giphy.gif', 'https://media.giphy.com/media/3ornka9rAaKRA2Rkac/200.gif', ARRAY['wave', 'hello', 'greeting'], 'greetings', 480, 480, false, false),
('High Five', 'Celebratory high five', 'https://media.giphy.com/media/3o7qDEq2bMbcbPRQ2c/giphy.gif', 'https://media.giphy.com/media/3o7qDEq2bMbcbPRQ2c/200.gif', ARRAY['high', 'five', 'celebration'], 'reactions', 480, 270, true, false),
('Shocked', 'Surprised and shocked expression', 'https://media.giphy.com/media/3o6wreo4BgGBLgrKx2/giphy.gif', 'https://media.giphy.com/media/3o6wreo4BgGBLgrKx2/200.gif', ARRAY['shocked', 'surprised', 'wow'], 'emotions', 480, 270, false, false),
('Sleepy', 'Tired and sleepy feeling', 'https://media.giphy.com/media/3o7qE1YN7aBOFPRw8E/giphy.gif', 'https://media.giphy.com/media/3o7qE1YN7aBOFPRw8E/200.gif', ARRAY['sleepy', 'tired', 'yawn'], 'emotions', 480, 270, false, false);
