import nodemailer from 'nodemailer';

if (!process.env.GMAIL_EMAIL || !process.env.GMAIL_APP_PASSWORD) {
  throw new Error("GMAIL_EMAIL and GMAIL_APP_PASSWORD environment variables must be set");
}

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.GMAIL_EMAIL,
    pass: process.env.GMAIL_APP_PASSWORD,
  },
});

interface ChatbotConversation {
  conversationHistory: string;
  timestamp: string;
  userId: string;
  userEmail?: string;
  messageCount?: number;
}

interface NewUserSignup {
  firstName: string;
  lastName: string;
  inviteCodeUsed?: string;
  inviteCodeOwnerName?: string;
}

export async function sendNewUserNotification(signup: NewUserSignup): Promise<boolean> {
  try {
    const fullName = `${signup.firstName} ${signup.lastName}`;
    let inviteInfo = '';
    if (signup.inviteCodeUsed && signup.inviteCodeOwnerName) {
      inviteInfo = `<p style="margin-top: 10px; color: #555;">Used invite code from <strong>${signup.inviteCodeOwnerName}</strong></p>`;
    }

    const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #333; border-bottom: 2px solid #4f46e5; padding-bottom: 10px;">
          New User added to MyKliq database
        </h2>
        ${inviteInfo}
        <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 30px 0;">
        <p style="color: #64748b; font-size: 12px; text-align: center;">
          This email was automatically generated by MyKliq.
        </p>
      </div>
    `;

    const textInvite = signup.inviteCodeUsed && signup.inviteCodeOwnerName
      ? `\nUsed invite code from ${signup.inviteCodeOwnerName}`
      : '';

    const textContent = `New User added to MyKliq database${textInvite}\n\n---\nThis email was automatically generated by MyKliq.`;

    const mailOptions = {
      from: process.env.GMAIL_EMAIL,
      to: 'futureshockholdings@outlook.com',
      subject: `MyKliq New User Signup - ${fullName}`,
      text: textContent,
      html: htmlContent,
    };

    const result = await transporter.sendMail(mailOptions);
    console.log('New user signup notification email sent:', result.messageId);
    return true;
  } catch (error: any) {
    console.error('Failed to send new user signup notification email:', error?.message);
    return false;
  }
}

export async function sendChatbotConversation(conversation: ChatbotConversation): Promise<boolean> {
  console.log('=== CHATBOT EMAIL DEBUG START ===');
  console.log('Gmail credentials present:', {
    email: !!process.env.GMAIL_EMAIL,
    password: !!process.env.GMAIL_APP_PASSWORD
  });
  console.log('Conversation data received:', {
    userId: conversation.userId,
    userEmail: conversation.userEmail,
    messageCount: conversation.messageCount,
    conversationLength: conversation.conversationHistory?.length || 0
  });
  
  try {
    const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #333; border-bottom: 2px solid #4f46e5; padding-bottom: 10px;">
          MyKliq Chatbot Conversation
        </h2>
        
        <div style="background-color: #f8fafc; padding: 15px; border-radius: 8px; margin: 20px 0;">
          <p><strong>User ID:</strong> ${conversation.userId}</p>
          <p><strong>User Email:</strong> ${conversation.userEmail || 'Not available'}</p>
          <p><strong>Timestamp:</strong> ${new Date(conversation.timestamp).toLocaleString()}</p>
          <p><strong>Message Count:</strong> ${conversation.messageCount || 'Unknown'}</p>
        </div>
        
        <div style="margin: 20px 0;">
          <div style="background-color: #f8fafc; padding: 20px; border-radius: 8px; border-left: 4px solid #4f46e5;">
            <h3 style="color: #4f46e5; margin: 0 0 15px 0;">Complete Conversation:</h3>
            <pre style="margin: 0; white-space: pre-wrap; font-family: 'Courier New', monospace; font-size: 13px; line-height: 1.5; background-color: #ffffff; padding: 15px; border-radius: 4px; border: 1px solid #e2e8f0;">${conversation.conversationHistory}</pre>
          </div>
        </div>
        
        <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 30px 0;">
        <p style="color: #64748b; font-size: 12px; text-align: center;">
          This email was automatically generated by the MyKliq Support Chatbot system.
        </p>
      </div>
    `;

    const textContent = `
MyKliq Chatbot Conversation

User ID: ${conversation.userId}
User Email: ${conversation.userEmail || 'Not available'}
Timestamp: ${new Date(conversation.timestamp).toLocaleString()}
Message Count: ${conversation.messageCount || 'Unknown'}

COMPLETE CONVERSATION:
${conversation.conversationHistory}

---
This email was automatically generated by the MyKliq Support Chatbot system.
    `;

    const mailOptions = {
      from: process.env.GMAIL_EMAIL,
      to: 'mykliqchatbot@gmail.com',
      subject: `[MyKliq Support] Chatbot Conversation - ${new Date().toLocaleDateString()}`,
      text: textContent,
      html: htmlContent,
    };

    console.log('Sending email with data:', {
      from: mailOptions.from,
      to: mailOptions.to,
      subject: mailOptions.subject,
      textLength: mailOptions.text.length,
      htmlLength: mailOptions.html.length
    });

    const result = await transporter.sendMail(mailOptions);
    console.log('Nodemailer response:', result);
    console.log('Chatbot conversation email sent successfully');
    console.log('=== CHATBOT EMAIL DEBUG END ===');
    return true;
  } catch (error: any) {
    console.error('=== CHATBOT EMAIL ERROR START ===');
    console.error('Failed to send chatbot conversation email:', error);
    console.error('Error details:', {
      message: error?.message,
      code: error?.code,
      command: error?.command
    });
    console.error('=== CHATBOT EMAIL ERROR END ===');
    return false;
  }
}
