import { MailService } from '@sendgrid/mail';

if (!process.env.SENDGRID_API_KEY) {
  throw new Error("SENDGRID_API_KEY environment variable must be set");
}

const mailService = new MailService();
mailService.setApiKey(process.env.SENDGRID_API_KEY);

interface ChatbotConversation {
  conversationHistory: string;
  timestamp: string;
  userId: string;
  userEmail?: string;
  messageCount?: number;
}

export async function sendChatbotConversation(conversation: ChatbotConversation): Promise<boolean> {
  try {
    const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #333; border-bottom: 2px solid #4f46e5; padding-bottom: 10px;">
          MyKliq Chatbot Conversation
        </h2>
        
        <div style="background-color: #f8fafc; padding: 15px; border-radius: 8px; margin: 20px 0;">
          <p><strong>User ID:</strong> ${conversation.userId}</p>
          <p><strong>User Email:</strong> ${conversation.userEmail || 'Not available'}</p>
          <p><strong>Timestamp:</strong> ${new Date(conversation.timestamp).toLocaleString()}</p>
          <p><strong>Message Count:</strong> ${conversation.messageCount || 'Unknown'}</p>
        </div>
        
        <div style="margin: 20px 0;">
          <div style="background-color: #f8fafc; padding: 20px; border-radius: 8px; border-left: 4px solid #4f46e5;">
            <h3 style="color: #4f46e5; margin: 0 0 15px 0;">Complete Conversation:</h3>
            <pre style="margin: 0; white-space: pre-wrap; font-family: 'Courier New', monospace; font-size: 13px; line-height: 1.5; background-color: #ffffff; padding: 15px; border-radius: 4px; border: 1px solid #e2e8f0;">${conversation.conversationHistory}</pre>
          </div>
        </div>
        
        <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 30px 0;">
        <p style="color: #64748b; font-size: 12px; text-align: center;">
          This email was automatically generated by the MyKliq Support Chatbot system.
        </p>
      </div>
    `;

    const textContent = `
MyKliq Chatbot Conversation

User ID: ${conversation.userId}
User Email: ${conversation.userEmail || 'Not available'}
Timestamp: ${new Date(conversation.timestamp).toLocaleString()}
Message Count: ${conversation.messageCount || 'Unknown'}

COMPLETE CONVERSATION:
${conversation.conversationHistory}

---
This email was automatically generated by the MyKliq Support Chatbot system.
    `;

    await mailService.send({
      to: 'futureshockholdings@gmail.com',
      from: 'noreply@mykliq.com', // You can change this to a verified sender
      subject: `MyKliq Chatbot Conversation - ${new Date().toLocaleDateString()}`,
      text: textContent,
      html: htmlContent,
    });

    console.log('Chatbot conversation email sent successfully');
    return true;
  } catch (error) {
    console.error('Failed to send chatbot conversation email:', error);
    return false;
  }
}